version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"  # Hostta 5000, containerda 80
    environment:
      - ASPNETCORE_ENVIRONMENT=Test
      - REDIS_CONNECTION=redis:6379   # Eğer kodda kullanıyorsan, bu şekilde env de geçilebilir
    depends_on:
      - redis

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  redisdata:
